// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// EMA200 과 MACD를 이용하여 
// © cth_release

//@version=5
strategy("EMA200 + MACD")
var last_long_stop_price = 0.0
var last_short_stop_price = 0.0
ema = ta.ema(close, 200)

[macdLine, signalLine, histLine] = ta.macd(close, 12, 26, 9)
hline(0) // zero line
plot(macdLine, linewidth = 1, color = color.blue)
plot(signalLine, linewidth = 1, color = color.orange)

long_start = ema > open and (ta.crossover(macdLine, signalLine) and macdLine < 0 and signalLine < 0)
long_stop = last_long_stop_price >= open or open >= (open - last_long_stop_price) * 2 + open
short_start = ema < open and (ta.crossunder(macdLine, signalLine) and macdLine > 0 and signalLine > 0)
short_stop = last_short_stop_price <= open or open - (last_short_stop_price - open) * 2 >= open

if long_start
    last_long_stop_price := low[1]
    strategy.entry("Long", strategy.long)

if long_stop
    strategy.close("Long")

if short_start
    last_short_stop_price := high[1]
    strategy.entry("Short", strategy.short)

if short_stop
    strategy.close("Short")
